inspircd/inspircd

src/modules/m_cloaking.cpp

5c7db14a5 made the cloak use hex-encoded hashes instead
of the binary output in master.

Fix a regression in m_cloaking

---

configure

This is not used and apparently there are some distros which do not include it as part of the system Perl as seen with this:
```
[04:24] <lalala> [abc@localhost inspircd-2.0.18]$ ./configure
[04:24] <lalala> Can't locate Data/Dumper.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./configure line 36.
[04:24] <lalala> BEGIN failed--compilation aborted at ./configure line 36.
[04:24] <lalala> how to fix it
```

Don't load Data::Dumper in the configure script.

---

src/modmanager_dynamic.cpp

Without this patch when you try to load a module with a path it does this:
[*] Loading module:	/path/to/module.so
[*]

Fix a blank error message when trying to load a module with a path.

---

src/commands/cmd_list.cpp

When +ps is set, handle it as +s (most restrictive) instead of +p

cmd_list: Give +s precedence to +p

---

include/modules.h

Also, deduplicate MODULE_INIT (we are using a default implementation of DllMain).

Fix modules not being versioned on Windows.

---

src/modules/m_spanningtree/fjoin.cpp

This value can be negative so it should be a signed long not an unsigned long.

Fix a snotice in m_spanningtree incorrectly using an unsigned long.

---

include/numerics.h
src/usermanager.cpp
src/xline.cpp

This behaviour is specified in RFC 1459 and is used by Charybdis and other IRC server implementations so we should probably also use it.

Use ERR_YOUREBANNEDCREEP instead of NOTICE when a user is banned.

---

src/modules/m_xline_db.cpp

This error was introduced in bbeb5ea3.

Fix xline reasons being truncated in m_xline_db.

---

docs/conf/modules.conf.example
src/modules/m_silence.cpp

Currently, it is possible for users to "mute" U-lined services through the use of m_silence. This should rarely, if ever, be desired behaviour.
Adds config options to m_silence to specify whether U-lined services should bypass silence mask(s).

Allow U-lined services to bypass m_silence (configurable)

---

make/test/compiler.cpp

Apparently I had c++ linked to my custom Clang variant which doesn't identify as GCC 4.2.1. Oops.

Fix oversight which caused problems with Clang on OSX.

---

src/userprocess.cpp

This bug looks serious but it can only be triggered due to a very unusual server configuration problem. If you haven't already had a crash then you probably aren't at any risk.
The way this crash happens is:
1. InspIRCd::DoBackgroundUserStuff is called by the main loop.
2. In the switch statement curr->registered is REG_NICKUSER so InspIRCd::AllModulesReportReady is called.
3. InspIRCd::AllModulesReportReady calls the OnCheckReady event in m_cgiirc.
4. m_cgiirc calls RecheckClass which sets the user's class to NULL and calls LocalUser::SetClass and LocalUser::CheckClass.
5. The user doesn't match any classes in LocalUser::SetClass so LocalUser::CheckClass quits the user with with "Access denied by configuration".
6. Control flow returns to InspIRCd::DoBackgroundUserStuff when …

[2.0] Fix a minor crash when a user has no class after OnCheckReady.

---

make/template/main.mk

This is a workaround for now. In 2.2 we should prefix all of the environment variables with INSPIRCD_ to avoid collisions.

[2.0] Fix building when VERBOSE is already set in the environment.

---

configure
make/common.pm
make/configure.pm
make/console.pm
tools/genssl
tools/test-build

Now we have dropped support for the old CentOS release we can use Perl 5.10 instead of 5.8. Yay!
**Note:** I'm not going to update `make/utilities.pm` as that file is scheduled to be removed soon anyway. Similarly, `./modulemanager` and the module bits of `./configure` are due to be entirely rewritten so i'm not going to update that either.

Convert build system to Perl 5.10.

---

docs/conf/modules.conf.example
src/modules/m_restrictmsg.cpp

As requested by @Adam-.
---
Whilst this is a change in behaviour I believe that it was caused by an oversight. Generally people do want their users to be able to message services even if they have messaging restricted.

[2.0] Fix not being able to message ulines when m_restrictmsg is loaded.

---

configure

This means that the settings the admin has previously configured with are no longer ignored when upgrading.
Reported by @Cronus89 on IRC.
---
The 2.0 build system really is the gift that keeps on giving. None of this needs to be merged into master as the code there has already been completely rewritten and works like it should.

[2.0] Fix configure overwriting the cache settings on startup.

---

src/coremods/core_dns.cpp

This fixes #973. Forward port of #974.

Fix IPv6 nameservers not being detected by the resolv.conf parser.

---

src/coremods/core_stats.cpp

This is a [widely used format](http://en.wikipedia.org/wiki/IPv6_address#Literal_IPv6_addresses_in_network_resource_identifiers) as without it the port is ambiguous.
Before:
:irc.example.com 249 NickName ::::6667 (clients, plaintext)
After:
:irc.example.com 249 NickName :[::]:6667 (clients, plaintext)
We also use this format in `irc::sockets::sockaddrs::str()`.

Encase the IPv6 address in `STATS p` with square brackets.

---

configure

Comparisons in Perl are sometimes really quite illogical.

[2.0] Fix mistakenly using Clang instead of GCC on older FreeBSD versions.

---

docs/conf/modules.conf.example
src/modules/m_nationalchars.cpp
win/CMakeLists.txt

This fixes some of the more serious problems with the nationalchars module:
- Strip the directory name in the default casemapping value. This prevents the entire path from being shown in ISUPPORT.
- Error out if the casemapping value contains a space. This prevents invalid entries in ISUPPORT.
- Error out if the locale file failed to load. This fixes the case where errors could be silently ignored which is the cause of some confusion.
- Fix relative file path when building on Windows. The executable is not in the bin directory on Windows.
- Install nationalchars files on Windows.

[2.0] Fix various issues with the nationalchars module.

---

make/template/org.inspircd.plist

This makes resolving configuration errors *so* much easier.

[2.0] Log STDOUT and STDERR in the launchd script.

---

make/gnutlscert.pm
make/opensslcert.pm

This converts this:
```
$ ./configure --generate-gnutls-cert
What is the hostname of your server?
[irc.example.com] -> 
What email address can you be contacted at?
[example@example.com] -> 
What is the name of your unit?
[Server Admins] -> 
What is the name of your organization?
[Example IRC Network] -> 
What city are you located in?
[Example City] -> 
What state are you located in?
[Example State] -> 
What is the ISO 3166-1 code for the country you are located in?
[XZ] -> 
How many days do you want your certificate to be valid for?
[365] -> 
Can't exec "certtool": No such file or directory at make/gnutlscert.pm line 142, <STDIN> line 8.
[CONFIGURE NOW CONTINUES INTO NORMAL INTERACTIVE MODE OBSCURING THE ERROR MESSAGE]
```
Into this:
```
$ ./configure --generate-gnutls-cert
Error: unable …
```

[2.0] Show a better warning when certtool/openssl are missing.

---

make/utilities.pm

From Perl 5.22 onwards, POSIX::tmpnam() has been deprecated (without the
usual 2 year deprecation cycle), using the File::Temp module instead
preserves compatibility while allowing compilation on 5.22 and later.
As it stands, Fedora Rawhide is failing like so:
Configuration failed. The following error occured:
Calling POSIX::tmpnam() is deprecated at make/utilities.pm line 407, line 32.

Replace deprecated tmpnam() call

---

configure
make/check_epoll.cpp
make/check_eventfd.cpp
make/check_kqueue.cpp
make/check_stdint.cpp
make/check_strlcpy.cpp

Reported by @Adam- who has recently joined the OS X master race.
It seems like the newer OS X versions don't put headers into the system include directories. Switch to using a test file instead.
The test file was backported from 2.2.

[2.0] Fix checking whether kqueue/stdint/strlcpy are available.

---

make/template/main.mk

The main makefile tries to parallelise things and does a debug and normal build at the same time which causes the linker to explode when it tries to link files from a debug and non debug build together. This patch makes it do one at a time which causes one of the builds to be a no-op.
This target is not propagated to the sub-makefile so it does not affect the parallelisation of the build. ~~The only thing it might slow down is the install target but thats so fast anyway it isn't a problem even on something ridiculously underpowered like a Raspberry Pi.~~ Edit: No it won't. I'm not sure why I thought it would.
This is a 2.0 fix only. I am working on something better than this for master.
Tested and working on both BSD Make 24 and GNU Make 3.81.

[2.0] Fix "make -jX debug install" causing linker errors.

---

src/channels.cpp

The `topicset` variable is the time the topic was changed last not whether there is a topic set.
Fixes #1091.

[2.0] Fix sending the wrong numerics on join when a topic is empty.

---

src/commands/cmd_kill.cpp

Suggested by @Adam-. Fixes #1015.

[2.0] Fix exposing the opers hostname in KILL when using hidekills.

---

src/inspircd.cpp

Just a mismatched type, improperly done cast in a printf statement.
Requested type to print is unsigned long, cast is to unsigned long, but variables force the type to unsigned long long because of a lack of brackets.

Fixed a build warning

---

make/configure.pm

In the new Xcode release Apple removed the LLVM version from the version string. This is a problem as our version detecting code relied on it.
To solve this we split off the Apple variant of Clang and treat it if it was a different compiler. This mirrors the change implemented by other build systems like CMake 3.0.

Fix detection of the Apple variant of Clang.

---

make/opensslcert.pm

The reason for this change is because a 1024-bit prime is feasibly factorable in a year by attackers with a large enough budget to do so.
This is a change in build system behaviour but it should not cause any problems although I have added a backwards compatibility switch just in case. In my opinion the aforementioned risk is big enough to justify this.
GnuTLS is not affected as it defaults to 2048-bit certificates by default.
References:
- https://freedom-to-tinker.com/blog/haldermanheninger/how-is-nsa-breaking-so-much-crypto/
- https://weakdh.org/imperfect-forward-secrecy-ccs15.pdf

[2.0] Generate a 2048-bit dhparams unless explicitly specified.

---

make/utilities.pm

This fixes the problems Jenkins was having on OS X.

Remove the PKG_CONFIG_PATH extension code from the build system.

---

src/modules/m_cap.cpp
src/modules/m_cap.h

[According to the cap-3.1 specification:](http://ircv3.net/specs/core/capability-negotiation-3.1.html)
>The capability identifier set must be accepted as a whole, or rejected entirely.
Our failure to follow the standard was apparently causing problems with irssi (according to @dequis).
This is a bit of a hack because I didn't want to have to rewrite the entire CAP API.

[2.0] Fix CAP REQ to be atomic like the standard dictates.

---

src/modules/extra/m_ssl_gnutls.cpp

This fixes the following warnings
`warning: '-pedantic' is not an option that controls warnings [-Wpragmas]` (it is on older versions)
`warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]` (only in C++11 which we don't use yet, when buildtool is done this will be the default)

Fix warnings when building under GCC 6.

---

src/modules/m_starttls.cpp

This is an InspIRCd-specific token which is pointless because:
1. You can't STARTTLS after registration is complete.
2. You can already discover STARTTLS support via cap `tls`.

Remove the STARTTLS token from ISUPPORT.

---

src/modules/m_httpd_stats.cpp

This patch adds command usage to httpd_stats. It is useful for our network but not tested in production yet. This feels like it should be togglable by configuration though, rather than to be included by default. Or maybe it could be included on a substring match of the URI? (e.g. /stats/?includeCommandList)

Adds <commandlist> tag with command usage to httpd_stats.

---

src/modules/m_spanningtree/fjoin.cpp
src/modules/m_spanningtree/postcommand.cpp

[Lintian](https://lintian.debian.org/) Debian packaging helper tool [report](https://lintian.debian.org/full/pkg-irc-maintainers@lists.alioth.debian.org.html#inspircd) some minor spelling error for printed message in module m_spanningtree.so. It's minor, but i'll be glad if included in future 2.0.x to drop this packaging minor patches in future Debian packages. Thanks.

Minor spelling errors in m_spanningtree.so

---

src/configparser.cpp

As with 402a1bb010522a35600325c1a3084e092b40ca22 this is known to be undefined behaviour but changing it is too risky for the 2.0 branch.

[2.0] Fix GCC 6 warning about null checking this.

---

docs/conf/modules.conf.example
src/modules/m_classban.cpp

This adds a module, connameban, that provides extban token 'n' that matches the mask against the users ->GetClass()->name.
This is not yet tested in production.
The IS_LOCAL() should work in all cases that are contained in master, since in those cases only local users are handled. Changing the signature of OnCheckBan to take a LocalUser* instead of a User* could make sense.
If not, I guess adding some sort of handling of the case where the user is not local would be necessary in this module, I'm not sure how to get that information across server nodes though.

Adds classban module providing extban 'n' for connect class ban.

---

make/template/inspircd

[2.0] Fix 'cron' and 'restart' in the helper not forwarding arguments.

---

.gitignore
make/common.pm
make/configure.pm
make/console.pm
make/template/main.mk

This is needed in a later commit so I extracted it to a helper method to reduce duplication.
An error message was using the context variable rather than the target file variable.
Instead of polluting the root directory generated files that do not have a specific location to go in are now put in the .configure directory.
Same as the previous but for the configure cache file.
Previously the configuration file parser would break if a value contained a double quote symbol.  The format has been simplified to just `<name> [value...]` to avoid needing to escape these.

Improvements to ./configure file generation.

---

make/template/main.mk

This will not affect 99% of users but its good to be sure just in case the user tries to dump module files into a global library directory.

[2.0] Delete modules cautiously when doing a deinstall.

---

include/modules.h
make/calcdep.pl
make/template/main.mk
src/coremods/core_info/cmd_modules.cpp
src/modmanager_dynamic.cpp
src/modmanager_static.cpp
tools/test-build

This implements the idea I said I would implement in #1009 for the user facing variables. The rest will be changed at a later date.
Jenkins might need some updates after this, cc @tobgen.

Rename vague build environment variables to prevent collisions.

---

make/template/main.mk

I have no idea how this happened considering that everything was green when I pushed it to Jenkins. I guess that Jenkins is just doing `make` instead of `make install`? Blah.
Thanks to @Robby- for reporting this.

[2.0] Fix extraneous quotes in makefile template.

---

.travis.yml
tools/travis-ci.sh

`travis-ci.sh` is only needed for insp20. On master the script can just use "./tools/test-build $CXX".

Add configuration for building with Travis-CI.

---

src/mode.cpp

If two modes with the same prefix rank are loaded (e.g. via `m_customprefix`) then only the last loaded mode would be shown in the PREFIX 005 token.
This fixes the underlying bug which #1178 worked around.

[2.0] Fix 005 not showing some modes with the same rank as others.

---

include/numerics.h
src/coremods/core_user/cmd_nick.cpp

This fixes InspIRCd to work like section 4.1.2 of RFC 1459 dictates.
Filed against master so we don't break anything relying on the old behaviour..

Fix sending the wrong numeric when an empty new nick is received.

---

configure
make/template/main.mk

Whilst this is undefined behaviour fixing all cases of this are too invasive for 2.0.

[2.0] GCC should never assume that this can not be null.

---

src/modules/m_stripcolor.cpp

The stripcolor mode (+S) is designed to prevent spam of color codes inside channels. This works fine for messages, but does not affect part messages. This PR will filter color codes out of part messages on channels where +S is set.

Stripcolor now strips from part messages

---

tools/travis-ci.sh

The system version of this library does not include support for pkg-config.

[2.0] Force link sqlite3 on OS X when doing Travis builds.

---

docs/conf/inspircd.conf.example
docs/conf/modules.conf.example
docs/conf/opers.conf.example

- Follow best current practises by using bcrypt almost everywhere
in the example configuration files.
- Document the existence of new hashing modules in master.

Update documentation for password hashing.

---

docs/conf/helpop-full.conf.example
docs/conf/inspircd.conf.example
src/coremods/core_oper/cmd_die.cpp
src/coremods/core_oper/cmd_restart.cpp
src/coremods/core_oper/core_oper.cpp

We could alternately make it an oper priv to die without the password. What do you think @attilamolnar?

Undocument <power> and set the default to the server name.

---

src/server.cpp

- Replace the deprecated MAXCHANNELS token with CHANLIMIT.
- Remove the deprecated FNC token (other implementations can force
a nick change without sending this token so informing clients of
that we might force a nick change is pointless)
---
References:
https://github.com/grawity/irc-docs/blob/master/client/RPL_ISUPPORT/draft-hardy-irc-isupport-00.txt#L922
https://github.com/grawity/irc-docs/blob/master/client/RPL_ISUPPORT/draft-hardy-irc-isupport-00.txt#L931
http://defs.ircdocs.horse/defs/isupport.html#fnc

Improve the default ISUPPORT tokens.

---

src/coremods/core_stats.cpp
src/modules/m_cloaking.cpp
src/modules/m_spanningtree/override_map.cpp

Now all formatting code goes through InspIRCd::Format and doesn't mess around with C arrays.

Replace snprintf usage with InspIRCd::Format.

---

src/modules/extra/m_geoip.cpp
src/modules/extra/m_ldap.cpp

1. The latest version of libGeoIP has commas at the end of an enumerator list which causes warnings as we are still using C++03.
2. OS X Yosemite has deprecated OpenLDAP in favour of Open Directory but like with OpenSSL it still works fine and is unlikely to be removed soon.

Fix various compiler warnings

---

.travis.yml
tools/test-build
tools/travis-ci.sh

- Switch Linux builds to Ubuntu 14.04 from 12.04
- Split dynamic and static builds into different jobs.
- Remove OS X builds as the infrastructure is slow and unreliable.
---
The Linux build time has now dropped to 7m30~ for Clang and 10m30~ for GCC. This is a time saving of just over 50%.
I have looked into precompiled headers but I don't think its possible with how flaky calcdep/unit-cc are at the moment (fixing this is work in progress).

Speed up Travis builds.

---

src/channels.cpp

We should only use OperMaxChans if they have the right privilege.

Fix compatibility with the legacy <channels> tag.

---

make/directive.pm

This fixes an oversight where in cases like #1224 you could not set the environment variables that the directive parser is looking for because of invalid characters.

Fix the directive parser using invalid environment variables.

---

src/modules/m_httpd_stats.cpp

The description of the local server is ``Sanitize()``'d before being printed, but those of other servers are not.
When the remote server uses a non-UTF-8 charset in its description, this causes the generated XML file to be invalid.

m_httpd_stats: Also sanitize other server gecos

---

docs/conf/modules.conf.example
src/modules/m_joinflood.cpp
src/modules/m_nickflood.cpp

- Allow use of human readable durations (e.g. 1m30) in flood modules.
- Make the duration of nickflood and joinflood configurable.

Improvements to flood modules

---

src/modules/extra/m_ssl_openssl.cpp

OpenSSL is developed by incompetent people who have never heard of deprecating something before removing it. That is all.

Fix OpenSSL build errors caused by BIO/BIO_METHOD now being opaque.

---

configure
modulemanager

For 3.0 I will work on a better fix for this but for 2.0 this just restores the old behaviour.
Thanks to @grawity for pointing this out.

[2.0] Workaround modern Perls not adding . to @INC.

---

src/socketengines/socketengine_epoll.cpp

ulimit cmd=4 is not implemented by musl libc.

socketengine_epoll: use getrlimit not ulimit

---

docs/conf/modules.conf.example

This makes it clearer to server admins that they shouldn't use m_chanprotect, m_halfop and the compat- modes in m_cloaking.

[2.0] Add a bigger warning about deprecated things being removed.

---

src/modules/m_spanningtree/protocolinterface.cpp

This fixes a bug noticeable with m_timedbans (a few people have mentioned it in #inspircd), where sending to a status of (eg.) '@' will still send to the entire channel. From what I can see of the code, it was a small oversight in some re-writes in the past. This was the safest way I seen to fix this.
I see 3 other modules use the PI->SendChannel... functions, and they use a status of 0, that tests fine with this.
I also see this appears fixed in master with PI being rewritten quite a bit. This would be nice to have fixed in 2.0.

Fix spanningtree protocol interface sending statusmsgs to whole channel

---

configure

This is the 2.0 equivalent of #1273.

[2.0] Use clock_gettime() on macOS 10.12.

---

configure
make/configure.pm

macOS now supports clock_gettime() but it is part of libSystem rather than librt which does not exist on macOS.

Fix the clock_gettime() test on macOS Sierra

---

docs/conf/filter.conf.example

- Fix tabs being used to align a config attribute instead of spaces.
- Remove warning which only applied to the old configuration format. If a user is still using this then they will have explicitly enabled it and already received a warning.

Fix some minor problems with the filter docs.

---

src/modules/m_cgiirc.cpp

If an IP address which is invalid is given then the IP address given to the user `webirc_ip` will contain junk. This is not as dangerous as it looks as the core will reject the invalid IP when SetClientIP is called. It should be rejected earlier than that though to prevent incorrect notices being given.
Some examples of things this patch prevents:
```
WEBIRC password * ###################################################################### :
WEBIRC password * ###################################################################### :invalid ipaddr here
```
---
Also penalise clients that use WEBIRC incorrectly (mostly useful for preventing trolls from spamming opers with invalid WEBIRC host messages).

[2.0] Fix WEBIRC not rejecting invalid IP addresses.

---

configure

GCC 7 may optionally omit the MINOR version number in dumpversion depending on the compiler flags it was built with.
This also fixes a potential bug which will appear when GCCVER/GCCMINOR is greater than 9.
Fixes #1309.

[2.0] Fix compiler version parsing on GCC 7.

---

src/users.cpp

This fixes #1229 and has been tested by @Robby- in production for a few days now.
```
[21:00]  <SaberUK>  Robby: how did that dnsbl patch go 
[21:00]  <Robby>    its still running
[21:00]  <Robby>    no issues thus far
```

[2.0] Invalidate the caches properly when User::SetClientIP is called.

---

src/modules/m_permchannels.cpp

[2.0] Warn when a user configures a permanent channel without +P.

---

modulemanager

Apparently not only is the Perl documentation on BEGIN block execution order wrong but in a BEGIN block any updates to the include paths are not applied until the end of the block. Yay!

[2.0] Fix ModuleManager not being able to find make::configure.

---

src/modules/m_sakick.cpp

This has never worked due to the channel lookup using the user's nick

m_sakick: remove unused "Unable to kick" notice

---

src/modules/m_override.cpp

Fix permission issue of m_override.cpp
@jdowny detected that an KICK-Override won't work if oper and target are halfops in same channel

fix override issue

---

configure

OpenBSD decided to remove `BSDmakefile` support because it is non standard (heaven forbid!) so our automagic makefile stuff no longer works. We can't do a lot about this other than warn OpenBSD users to run a different command instead.
Ref: https://github.com/openbsd/src/commit/7c8e039b953a21c37b44a481b0a7b62a845164dc
See also: #1332

[2.0] Tell OpenBSD users that they need to use a different make command.

---

make/configure.pm
make/test/clock_gettime.cpp
make/test/compiler.cpp
make/test/compiler_info.cpp

Its clear that parsing version output is not reliable enough (see #1309) so switch to using a method which is less likely to break.

Switch compiler detection to use a more reliable method.

---

configure

Just some low hanging fruit left over from before we had `print_error` and from when you could change the socket engine in interactive mode.

Tidy up the socket engine selection code.

---

configure

Apparently even though its 2017 and there are much better options for virtualisation available this is still a problem that people need to be warned about.

Warn the user about clock drifting when running on OpenVZ.

---

include/socketengine.h
src/socketengine.cpp
src/socketengines/socketengine_epoll.cpp
src/socketengines/socketengine_kqueue.cpp
src/socketengines/socketengine_ports.cpp
src/socketengines/socketengine_select.cpp

The write counters were close to useless because they were only
incremented on a write "event" which is only triggered when writing
would block.
Read handling was a little more useful in that all reads must happen
through the socket engine, so these were happening at the correct time,
but we can clean this up by doing it in the SE itself rather than each
platform port.
This means that both read and write events are now easily and usefully
defined as "a syscall of either read or write was attempted".
We also count empty read and write events as being an event, because
they still were an attempt to poll a socket in some way. This may help
to identify "bad" code which is repeatedly trying to read a socket for
some reason.
Lastly, we check for failed read/write calls, and log them as an error …

Improve and centralize socket engine event counters.

---

.mailmap

This cleans up the author list when running git-shortlog and other similar commands.
More details: https://git-scm.com/docs/git-shortlog#_mapping_authors

[2.0] Add a mailmap to clean up the output of git-shortlog.

---

include/configparser.h
include/configreader.h
include/typedefs.h
src/configparser.cpp
src/configreader.cpp
src/modules/m_httpd_config.cpp

… and now the config is stored in a sane way make the config system case insensitive

Store config values in a map instead of a unique vector of pairs.

---

src/modules/m_sasl.cpp

This allows services to implement alternate mechanisms that use the SSL fingerprint.

Always append the SSL fingerprint even if EXTERNAL is not used.

---

docs/conf/inspircd.conf.example
src/modules/m_cgiirc.cpp

I have also renamed the `client` field to `gateway` to match the IRCv3 WebIRC specification.
http://ircv3.net/specs/extensions/webirc.html

Allow filtering WebIRC connections into a connect class by gateway.

---

src/modules/m_blockcaps.cpp
src/modules/m_noctcp.cpp

Previously we assumed that CTCP ACTIONs matched "\1ACTION ". This is incorrect because "\1ACTION\1" and "\1ACTION" are valid CTCPs.

[2.0] Fix exempting CTCP ACTIONs in m_blockcaps and m_noctcp.

---

src/modules/m_dnsbl.cpp
src/modules/m_spanningtree/main.cpp
src/socket.cpp
win/README.txt
win/inspircd_win32wrapper.cpp
win/inspircd_win32wrapper.h

I think it is safe to say that nobody should be using XP to host an IRC server, especially now that GnuTLS doesn't support XP anymore.
This pull request also bumps the minimum Visual Studio version to 2015 which removes a massive chunk of code now that Microsoft have decided to follow standards. This should not be a problem as the free community edition can be downloaded at https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx

Purge code for Windows XP and MSVC pre-2015.

---

configure

Seems like it got overlooked in 8270aca2ee161ffa9a93243016266a2681b6d7ba

Fix SCRIPT_DIR directory change

---

src/modules/m_rline.cpp

RLines currently only check for a match including the User's host and not the IP. This may have been intentional but I believe to be an oversight.
One may wish to set an RLine using a portion of the IP and it stands the chance of not matching if their IP resolves to any host.
This PR replaces #1358

Make RLines match against IP as well as host

---

docs/conf/modules.conf.example
src/modules/m_sasl.cpp

Back when the SASL `target` variable was introduced (commit 8cb1935360087b4e38802b837981e5f41e9b87d7), the example config wasn't updated and it's not a very well known config variable. This variable allows the ENCAP message to return false if the server isn't available (ie, Services are offline). Though currently, even when used it just sends a SASLFallback event that (afaik) is not caught anywhere.
The issue here is that if Services are down and a client is connecting and sees SASL available (through CAP), it requests it, gets acknowledged and tries to use it. The message either sends to all servers (default target of '*') or fails to send to the target server. The client sits there waiting for a response, until registration timeout hits. We can't do much with sending to all servers and …

2.0: Inform the client when a SASL message cannot be sent

---

docs/conf/modules.conf.example

This fixes a docs issue that refers to m_sqloper and m_sqlauth both as extras modules, despite the fact that they are not.

Fix referring to sqloper and sqlauth as extras in modules.conf.example.

---

src/channels.cpp

This fixes a reversion from ebe5b201aab71cf2ead1e068889be736314fbb73. See https://github.com/inspircd/inspircd/commit/ebe5b201aab71cf2ead1e068889be736314fbb73#diff-e8d9cb9a964b4f01c8b7d5fd3676aecbL480 for the specific place of the reversion.
GetExtBanStatus was passing the full ban mask to CheckBan, i.e. "m:\*!\*@\*" instead of removing the extban prefix first. This resulted in no extbans matching. Additionally, GetExtBanStatus checked all ban masks instead of just ones that began with an extban prefix, resulting in users that have a banmask apply to them (i.e. +b \*!\*@\* and in the channel on +e \*!\*@\*) matching all GetExtBanStatus calls.
Thanks to @genius3000 for his assistance in isolating the precise commit and line.

Fix action extbans not triggering

---

docs/conf/modules.conf.example

It's something small but noteworthy nonetheless

Remove extra double quote (") from modules.conf

---

docs/conf/modules.conf.example
src/modules/m_override.cpp

This adds the optional user mode "O". If the user mode is enabled, then only opers who have given it to themselves may use oper override. If the user mode is disabled (default if config option left blank), then override works normally.
Requiring a usermode for override to work requires opers to actively enable overriding in order to prevent accidental overrides. This allows opers to continue to act as normal users when not doing oper-related tasks. In my opinion, this was worth it because override, unlike SA*, is focused solely on the operator rather than other users (SAJOIN can be used on others).
This resolves https://github.com/inspircd/inspircd/issues/363.

Add optional oper override umode +O

---

src/coremods/core_user/cmd_nick.cpp
src/modules/m_nonicks.cpp

Currently, when a user attempts /NICK while on a channel that they're banned on, the server returns a "cannot send to channel" message. This PR changes that to a "cannot change nick" message, which makes more sense given the context of a nick change and not a PRIVMSG.
The second clarification is small: this changes "can't" to "cannot" in m_nonicks simply to match the precedent set by other error messages.

Clarify error message when attempting to /NICK while banned

---

src/modules/m_filter.cpp

There was an oversight in https://github.com/inspircd/inspircd/pull/1264, where G-Lines as a result from a PART/QUIT message filter were not broadcast to opers via snomask.

Add snomask alert on m_filter quit/part G-Line

---

include/numeric.h
include/numerics.h
src/coremods/core_channel/cmd_invite.cpp
src/coremods/core_channel/cmd_join.cpp
src/coremods/core_channel/cmd_kick.cpp
src/coremods/core_channel/cmd_names.cpp
src/coremods/core_channel/cmd_topic.cpp
src/coremods/core_privmsg.cpp
src/coremods/core_user/cmd_mode.cpp
src/coremods/core_user/cmd_part.cpp
src/modules/m_cycle.cpp
src/modules/m_knock.cpp
src/modules/m_namedmodes.cpp
src/modules/m_redirect.cpp
src/modules/m_remove.cpp
src/modules/m_satopic.cpp
src/modules/m_timedbans.cpp
src/modules/m_uninvite.cpp

Per #1122, this PR replaces multiple instances of ERR_NOSUCHNICK with the proper channel numerics. This includes mostly ERR_NOSUCHCHANNEL, but also a couple of ERR_NOTONCHANNEL instances.

Fixed misc. instances of ERR_NOSUCHNICK instead of channel numerics

---

docs/conf/inspircd.conf.example
docs/conf/modules.conf.example

This fixes the copypasta in the description for operspywhois and properly comments the <channames> and <chanprotect> tags in modules.conf.example. This resolves #1448.

Fix two minor docs issues

---

src/modules/m_banredirect.cpp

During a netburst, the banredirect `ModeWatcher::BeforeMode` is called with as if the ban was being set, resulting in the metadata being duplicated for the ban. This second metadata object will not be removed when the ban is unset, resulting in a "ghost ban" where there is no ban matching a user, but they are still redirected to the redirect channel.
1. Have 2 servers, `SA` and `SB`.
2. Have 2 users, `UA` and `UB` on `SA` and `SB` respectively.
3. Both users join `#channel` and `UA` gets op.
4. `UA` joins `#otherchannel`.
5. `UA` sets `MODE #channel +b UB!*@*#otherchannel`.
6. `UB` parts `#channel` and attempts to rejoin, leading to them being forwarded to `#otherchannel`.
7. `SA` and `SB` split.
8. `SA` and `SB` reconnect.
9. `UB` is still banned from `#channel` and forwarded to …

[2.0] Make sure banredirect metadata can not be duplicated

---

make/template/main.mk
src/coremods/core_stats.cpp

Compiled on hrev51795, with the modern GCC. on gcc2h, run `setarch x86` first.
I also tried compiling `m_regex_posix`, `m_regex_stdlib`, and `m_ssl_openssl` because those have devel libs by default.
cc @SaberUK

Add Haiku support

---

docs/conf/inspircd.conf.example
docs/conf/opers.conf.example
include/configreader.h
src/configreader.cpp
src/coremods/core_whois.cpp

This separates secret channels from non-secret channels when users WHOIS themselves.
This resolves #969.

Separate secret and private channels on whois for non-opers

---

src/coremods/core_channel/core_channel.cpp

Fixes #1091. It looks like this was already fixed, and then somehow reverted in the move to modularity.
PRing against master because of the discussion in aforementioned issue.

Do not send unset topics on channel join per RFC

---

src/modules/extra/m_geoip.cpp

I've tested this for both normal user and webirc connections using netcat; limiting the update to after NICK/USER have been sent keeps the GeoIP check to 1 during a normal user and to just 2 during webirc (as intended). Untested with pass/ident cgi:irc methods but they run off `OnUserRegister()` which is called right after `NICK` or `USER` (whichever is sent second).
Fixes #1470

[2.0] Update the GeoIP ExtItem when CGI:IRC sets the real IP

---

src/coremods/core_channel/core_channel.cpp

https://github.com/inspircd/inspircd/commit/b3a728d93f134684593576f8eaaf2daf8df39340 broke m_redirect by causing core_channels to return a MOD_RES_DENY if limitmode was set before m_redirect's hook could run. This fixes that issue by prioritizing core_channels' OnUserPreJoin to run after other modules, matching the behavior it had while in core.

Prioritize checking for +ikl last to match previous behavior

---

src/modules/m_repeat.cpp

* Validate the settings in the same order as the parameter syntax
* Always validate `Lines` and `Secs`
* previously you needed to set a `Diff` value for `Lines` and `Secs` to be validated
* Check `Backlog` for greater than _Max_
* previously `Backlog` was only checked against being disabled

Improve settings validation in m_repeat

---

src/modules/m_cgiirc.cpp
src/xline.cpp

This PR accomplishes two things:
1. Fixes CGI:IRC checking E-Lines on a user while their host is still that of the CGI:IRC server. Which allows a false match to happen and remain.
2. Fixes the ELine::Matches() function to not return 'false' when the user is already marked exempt (previously matched an E-Line). Looking in the history, this was fixed once already and reverted as it caused issue #989.  
I believe that the root cause of this issue was the user's host still being the CGI:IRC server which was E-Lined, as it had to match an active E-Line in order to return 'true' again. This is fixed as commit 1 here.  
To the best of my searching, the `user->exempt` flag is set:
* upon initial connection by checking for E-Lines matching the user (if a matched E-Line is returned, set true; else …

[2.0] Properly check E-Lines in general and specifically from CGI:IRC

---

include/listmode.h
src/listmode.cpp

This fixes an issue where after https://github.com/inspircd/inspircd/commit/d5a6054948502625d7f0c235f6faaeea58734de5, attempting to view the list for a listmode will cause a "You must specify a parameter" error under https://github.com/inspircd/inspircd/commit/d5a6054948502625d7f0c235f6faaeea58734de5#diff-34903a46f53c58683aa794a80721ce8eR92.

Fix an invalid mode parameters numeric upon attempting to view listmodes

---

src/coremods/core_channel/cmd_names.cpp
src/inspsocket.cpp
src/users.cpp

This PR optimizes loops inside of InspIRCd's core to remove redundant function calls and unnecessary memory reallocation. For most of the files affected here, that means STL optimization in the for loops. For users.cpp, a few redundant calls to mathematical operations in the write function (very commonly used) were optimized.

Optimize multiple redundant function calls in core

---

docs/conf/helpop-full.conf.example
docs/conf/helpop.conf.example
docs/conf/inspircd.conf.example
docs/conf/modules.conf.example
include/protocol.h
include/server.h
src/coremods/core_user/cmd_user.cpp
src/modules/m_chgname.cpp
src/modules/m_dnsbl.cpp
src/modules/m_gecosban.cpp
src/modules/m_httpd_stats.cpp
src/modules/m_setname.cpp
src/modules/m_spanningtree/compat.cpp
src/modules/m_spanningtree/protocolinterface.cpp

Currently, "gecos" is used in the `ServerInfo` class for "description" and in the `User` class for "real name", named (in `User`) "fullname".  
This PR is:
* Changing the ServerInfo "gecos" field to "description", only a few small changes here.
* Changing documentation and server sent messages that use "gecos" to mean "real name" to use a more clear form of "real name", "realname", "name" (whichever fits best with the current adjacent form).
The module m_gecosban example in modules.conf.example remains with "Gecos" as the primary name, as it fits the alphabetical order of the file and needs to remain the module name (2.0 compat).
Edit: more changes regarding "realname" to come at a later time.
~~With staying clear of compat issues for now, I would still like to accomplish in this PR:~~ …

Use "real name" to refer to the real name field.

---

src/modules/m_shun.cpp

This fixes an issue where, if a shunned user parted a channel, their PART message would be truncated to nothing rather than deleted. This resulted in users who leave with a message leaving with "" as their message, whereas shunned users executing PART with no message would cause expected behavior.

Fix blank instead of empty PART message when a user is shunned

---

docs/conf/helpop-full.conf.example
docs/conf/helpop.conf.example
docs/conf/inspircd.conf.example
docs/conf/modules.conf.example

* Improve exemptchanops in inspircd.conf.example (`<options>`) and modules.conf.example; along with both helpop examples.
* Add "the" to all "requires X module" in both helpop examples.
* Add SNOMASK 'r' and 'R' (OPERLOG) to both helpop examples.
* Clean up unnecessarily split SNOMASK lines in both helpop examples.
* Move chmode 'g' to be in alphabetical order in both helpops examples.
* Specify the needed mask formats for TLINE in helpop-full example.
* Remove extra `\` in RLINE mask format in helpop-full example.
Resolves #1481

Improve some documentation

---

docs/conf/modules.conf.example
src/modules/m_chanfilter.cpp
src/modules/m_filter.cpp
src/modules/m_muteban.cpp

Optionally do not notify users if their messages are blocked by certain modules.
This fixes issue #711, although that issue only mentions `filter`, the `chanfilter` and `muteban` modules also needed this change.
Ported to master as requested in #1096.

Optionally do not notify users if their messages are blocked by certain modules.

---

include/configreader.h
src/inspircd.cpp

I'm trying to eliminate as many unneeded PID files as possible from my system (the init scripts don't use them to identify running services), but there's currently no way to tell InspIRCd not to generate one. This PR implements a `--nopid` command line option, which prevents any PID file from being written to the file system, whether at the default location or the one specified in `<pid file>`.
Although this PR is against the master branch, it's straightforward to backport it to 2.0. I've already done all the work, and can submit a separate PR against the `insp20` branch for that if you like.

Add --nopid command line option

---

src/modules/m_kicknorejoin.cpp

This adds a check for if a kicked user has received a `/invite`, and if so, allows them to join and removes them from the list of blocked joins. This makes +J consistent with 'expected' behavior of `/invite`.

Make kicknorejoin respect /invite

---

src/coremods/core_channel/core_channel.cpp
src/coremods/core_info/core_info.cpp
src/coremods/core_loadmodule.cpp
src/coremods/core_oper/cmd_die.cpp
src/coremods/core_oper/cmd_restart.cpp
src/coremods/core_oper/core_oper.cpp
src/coremods/core_oper/core_oper.h
src/coremods/core_whois.cpp
src/listmode.cpp
src/modules/m_alias.cpp
src/modules/m_censor.cpp
src/modules/m_cgiirc.cpp
src/modules/m_chanlog.cpp
src/modules/m_customtitle.cpp
src/modules/m_dccallow.cpp
src/modules/m_dnsbl.cpp
src/modules/m_flashpolicyd.cpp
src/modules/m_helpop.cpp
src/modules/m_hidelist.cpp
src/modules/m_hidemode.cpp
src/modules/m_httpd_acl.cpp
src/modules/m_inviteexception.cpp
src/modules/m_pbkdf2.cpp
src/modules/m_restrictchans.cpp
src/modules/m_securelist.cpp
src/modules/m_vhost.cpp

Atomic rehashing allows us to ensure that an invalid configuration doesn't get partially applied before erroring or remove existing settings and not add them back, thus causing unexpected behavior.
Mostly minor changes to only apply changes to a module's config if it does not error.
- Refactor of `core_info` including changes to the `CommandDie`/`CommandRestart` structure and functionality
- `m_vhost` and `m_customtitle` got new config objects to allow easier loading of their configs instead of reading them on command execution
- Restructured loading and configuration of `m_pbkdf2` providers to make the rehash atomic, added config data objects
- And various `typedef`s for type reuse throughout

Make more modules rehash atomically

---

include/consolecolors.h

- Disables console colors when not attached to a TTY
- Add a preprocessor option to disable console colors completely

Add the ability to disable console colors in stdout logging

---

src/modules/m_dnsbl.cpp

This makes it consistent with other <connect> class parameters like
`webirc`

Allow wildcards in <connect:dnsbl>

---

include/inspsocket.h
include/users.h
src/coremods/core_xline/core_xline.cpp
src/inspsocket.cpp
src/modules/m_cgiirc.cpp
src/modules/m_haproxy.cpp
src/users.cpp

Make sure to recheck clones and connect classes when changing a
user's endpoint
Also moves all rechecks in to `SetClientIP()` so modules don't have to worry about it

Redo OnSetEndPoint logic to fix duplicate clones

---

src/modules/m_spanningtree/capab.cpp

If the casemapping is set to ascii, advertise the m_ascii module to 2.0
to allow use of the m_ascii extras module for 2.0

Add translation for casemapping between 2.0/3.0

---

include/xline.h
src/coremods/core_xline/cmd_eline.cpp
src/coremods/core_xline/cmd_gline.cpp
src/coremods/core_xline/cmd_kline.cpp
src/coremods/core_xline/cmd_qline.cpp
src/coremods/core_xline/cmd_zline.cpp
src/modules/m_cban.cpp
src/modules/m_rline.cpp
src/modules/m_shun.cpp
src/modules/m_spanningtree/delline.cpp
src/modules/m_svshold.cpp
src/xline.cpp

Add the X-line reason to the removal `SNOTICE`, matching the newer behavior of the expiry `SNOTICE`. This modifies `XLineManager::DelLine()` to require a string reference (`reason`) passed to it, which it assigns the X-line reason to if it is found and being removed.  
I had considered doing something like `DisplayExpiry()` in the core, but as removals are command based not core based (as expiring is) that seemed incorrect.
Idea/Request by @Robby-.

Add the reason to X-line removal notices.

---

include/modules/ssl.h

This fixes a minor typo created when the IsUsable check was moved to GetFingerprint. certificate is not defined-- rather, the variable here is cert.

Fix a minor typo in ssl.h

---

include/modules/httpd.h
src/modules/m_httpd.cpp
src/modules/m_httpd_acl.cpp
src/modules/m_httpd_config.cpp
src/modules/m_httpd_stats.cpp

- Improves URI parsing to properly read the separate portions (`path`, `query`, `fragment`)
- Add filter and sort options to `/stats/users`
- `sortby` (accepts `nick` and `idle`)
- `limit`
- `showunreg`
- `localonly`
- `desc`
- Add more data to `/stats/users`
- `signon`
- `lastmsg`
- `age`
- `local`

Expand searching in m_httpd_stats, add global handling of GET parameters

---

src/socket.cpp

Allowing spaces here can cause a whole host of issues as the user's host would contain a space unless set otherwise by webirc, haproxy, or similar.

Don't allow spaces in UNIX listener paths

---

include/inspircd.h
src/coremods/core_xline/cmd_eline.cpp
src/coremods/core_xline/cmd_gline.cpp
src/coremods/core_xline/cmd_kline.cpp
src/coremods/core_xline/cmd_qline.cpp
src/coremods/core_xline/cmd_zline.cpp
src/helperfuncs.cpp
src/modules/m_cban.cpp
src/modules/m_dccallow.cpp
src/modules/m_dnsbl.cpp
src/modules/m_rline.cpp
src/modules/m_shun.cpp
src/modules/m_spanningtree/addline.cpp
src/modules/m_svshold.cpp
src/modules/m_timedbans.cpp
src/xline.cpp

This adds a (helper) function of `InspIRCd::DurationString(time_t)` that returns a string containing the duration in a human-readable format. The format matches that of current InspIRCd duration inputs (ex: 1y20w2d3h5m9s). The function is based off Anope's `Anope::Duration()`, modified to add weeks and output short text format.
Switched to use this function:
* X-line expiries: from `600 seconds ago` to `10m ago`.
* X-line additions: from `expires on <date>` to `expires in 1d12h (on <date>)`.
* Timed ban additions: from `lasting for 600 seconds` to `lasting for 10m`.
* DCC Allow: from `for 600 seconds` to `for 10m`.
Closes #1574.

Add a function for displaying human-readable durations.

---

src/coremods/core_user/cmd_mode.cpp

Whenever a mode has a parameter, no modes past that mode will be shown
in RPL_CHANNELMODEIS.
References to items in a vector break when the vector's size is changed.

Fix not showing all modes on a channel

---

include/xline.h
src/configreader.cpp
src/modules/m_filter.cpp
src/modules/m_xline_db.cpp
src/xline.cpp

* Prevent xline_db from saving config X-lines as this is unnecessary and can cause weirdness or 'almost' duplicated X-lines to exist.
- On Rehash:
* Allow a config X-line to replace an existing X-line if:
* The existing X-line is not a config line, or
* The existing X-line is a config line but the reason changed.
* Compare the existing X-lines to a list of the newly read config X-lines and only expire those that are no longer configured.  
This prevents the extra noise during a rehash by only expiring the `badhost, badip, badnick, and exception` tags that were actually removed. If any of the aforementioned tags have a changed `reason`, the existing X-line will be expired and the new one added (mimicking behavior of the forced removal). Also allow the replacement (expire and add new) of an …

Improve the handling of config X-lines and filters.

---

src/xline.cpp

> When DefaultApply() adds a hit to the BanCache it uses the X-line duration to set a duration on the entry. This can result in an entry lasting longer than the X-line itself. Fix this by setting the entry duration to the time left on the X-line.
Example: G-line `*@xxx.*` for 5m. Wait 4m, connect a matching client, attempt registration and get banned. Try connecting again and note the instant block, as BanCache is working. Wait roughly 1m (expiry of G-line) and run /stats g to force expiry. Try connecting again, the BanCache entry still exists and will for another 4m, blocking connection.

Fix BanCache entries existing after X-line expiry.

---

docs/conf/opers.conf.example
src/modules/m_noctcp.cpp

Found an incorrect ModResult return when adding the oper privs, allowing the CTCP to still go through when "blocked" to a user target. This corrects that and adds the oper privs for both channel and user targets.
Resolves #1591.

noctcp: Bugfix and add oper privs to allow overriding.

---

src/mode.cpp

> Oper-only channel modes are currently unsettable by any channel op, oper or not. Correct this by checking both directions of an oper-only channel mode and continue only checking the setting of
an oper-only user mode. As anyone should be able to unset their own user modes and UnOper() removes all oper-only user modes automatically.
This keeps proper removal of oper-only user modes during UnOper() and prevents non-opers or opers without the given channel mode permission from removing said channel modes.

Check perms for removal of oper-only channel modes.

---

docs/conf/helpop.conf.example
docs/conf/modules.conf.example
docs/conf/opers.conf.example
src/modules/m_deaf.cpp

This merges the 2.0 extras module `m_privdeaf` (usermode +D for deaf to user messages and notices) as they have a similar purpose. Also improve some logic in the original deaf code and tidy up comments.
Updated the documentation with the previously undocumented configuration to deaf and the new privdeaf configuration.

Merge extras/m_privdeaf into m_deaf and update documentation.

---

make/unit-cc.pl

Link flags must be after compiled objects.
Otherwise, when loading objects, it can't find symbols.

Link flags must be after compiled objects.

---

src/modules/m_spanningtree/treesocket2.cpp

When a user (U1) sends a PRIVMSG to a server (S1), which sends it to S2, which finally
sends it to S3 to send to U2, S2 doesn't send the tags it received on
the command from S1 to S3.

m_spanningtree: Ensure tags are sent in forwarded cmds

---

docs/sql/sqloper.pgsql.sql
src/modules/m_sqloper.cpp

This PR fixes PostgreSQL compatibility with m_sqloper in InspIRCd 3.0. There were two issues:
First, the PostgreSQL module treats GetRow differently, and as such the row data needed to be cleared at the end of adding an OPER block in sloper.
Second, 1/0 are not synonymous with true/false in PostgreSQL boolean language.

Fix compatibility issues between sqloper and postgres

---

docs/conf/inspircd.conf.example
docs/conf/modules.conf.example

Clarify the require* connect block options and document the sslinfo module operonly option.

---

src/modules.cpp
src/server.cpp

inspircd.h defines __STDC_LIMIT_MACROS to ensure that C99 int type limits are defined, however, if <stdint.h> is included implicitly before inspircd.h, the build fails due to the C99 integer type limits being undefined.

Re-order the includes to fix C++03 builds.

---

src/modules/m_spanningtree/capab.cpp

If the first module in `modlist` is skipped by the initial checks, `i` will never be `modlist.begin()` so there will be an extra space at the beginning of the line. The addition of `m_ascii.so` doesn't handle a space at all. This fixes both issues by always adding a space at the beginning and then just trimming it off at the end.

[3.0] Fix space separation for CAPAB module list

---

configure

There was a typo or copy-paste error, making configure invoked with --system overwrite the
passed --log-dir option with the value of --module-dir

configure: --log-dir in --system mode uses the value for --module-dir

---

src/modules/m_haproxy.cpp

If the command is LOCAL, the address length isn't set before it is used
in ReadProxyAddress()

m_haproxy: Initialize address length to 0

---

include/inspsocket.h
src/inspsocket.cpp
src/modules/m_httpd.cpp

Currently m_httpd writes one buffer's worth of data before closing the socket, this fix makes it write the entire buffer and only close once it finishes.

Fix sending large pages in m_httpd

---

src/modules/m_haproxy.cpp

Just an order warning, moved the new initialization line.

Fix a compiler warning introduced in d107093.

---

src/coremods/core_channel/cmd_topic.cpp

Currently an oper cannot see the topic of a secret channel they aren't in using TOPIC. This was reported on IRC by @KoraggKnightWolf. The priv 'channels/auspex' would imply they should be able to, as LIST will show the topic of such a channel.
Add a check to TOPIC to match the behavior of LIST and meet the expectation.

Allow opers with 'channels/auspex' to see a secret channel topic.

---

src/modules/extra/m_ldap.cpp
src/modules/extra/m_mysql.cpp
src/modules/extra/m_regex_re2.cpp
src/modules/extra/m_sqlite3.cpp
src/modules/extra/m_ssl_gnutls.cpp
src/modules/extra/m_ssl_openssl.cpp
src/modules/m_httpd.cpp
src/modules/m_sha256.cpp

This allows the disabled warnings to still be applied to the rest of the source code while ignoring the vendored `http_parser.c`.

Reset diag pragmas after including external headers

---

src/helperfuncs.cpp

Currently a duration of 52w will return a blank string.
When I added weeks to the calculations, I failed to update the number of seconds to a year. As 365 days and 52 weeks aren't the same, but the calculation needs to be consistent.

DurationString(): Fix years being offset from weeks.

---

src/helperfuncs.cpp

Usually a duration of 0 is not allowed or handled separately, but it can also be used as a 'no set time' without separation.
Case in point: m_chanhistory calls DurationString() to convert the max time seconds back to a human readable string for the mode serializer. Returning a blank string is bad here.

DurationString(): Return "0" for a duration of 0.

---

src/modules/extra/m_geo_maxmind.cpp

I was showing as connecting from Japan while connected via a UNIX socket. Now it shows the expected "unknown".

m_geo_maxmind: Skip UNIX sockets in GetLocation().

---

src/listensocket.cpp
src/socket.cpp

Doing the removal in BindPorts() would remove the socket during a rehash and not recreate it. Now it's only removed if it's about to be created.
Resolves #1681.

Move UNIX socket removal to ListenSocket ctor.

---

src/modules/m_dnsbl.cpp

> A '.' gets added to the end of `reversedip` when creating the DNSBL hostname (L399) for the resolver. We need to remove the trailing '.' on the IPv6 form of `reversedip` or the resolver will fail.
`m_dnsbl: Reversed IP 172.110.28.43 -> 43.28.110.172`
`m_dnsbl: Reversed IP 2604:880:a:6::629 -> 9.2.6.0.0.0.0.0.0.0.0.0.0.0.0.0.6.0.0.0.a.0.0.0.0.8.8.0.4.0.6.2.`
IPv6 lookup throws SNOTICE: `DNSBL: An error occurred whilst checking whether 715AAAAAD!715AAAAAD@2604:880:a:6::629 (2604:880:a:6::629) is on the 'DroneBL' DNS blacklist: Request timed out`
`m_dnsbl: Reversed IP 172.110.28.43 -> 43.28.110.172`
`m_dnsbl: Reversed IP 2604:880:a:6::629 -> 9.2.6.0.0.0.0.0.0.0.0.0.0.0.0.0.6.0.0.0.a.0.0.0.0.8.8.0.4.0.6.2`
and no error on IPv6 lookup.

Fix DNSBL lookups for IPv6.

---

src/modules/m_silence.cpp

When silence mask is prefixed by + or -, it should only remove the first character, not the entire string.

Fixing SILENCE command

---

docs/conf/helpop.conf.example

Add repeat to the list of possible restriction types to exempt in helpop.conf.example.
Fixes #1714.
It was missing from the list of possible restriction types to exempt.
Not applicable
Not applicable

Add repeat to the list of possible restriction types to exempt in helpop.conf.example.

---

src/modules/m_hidemode.cpp

Adds the oper privilege of `channels/auspex` as an exemption to m_hidemode. So opers with that privilege will see hidden modes.
Resolves #1716.
**Operating system name and version:** Ubuntu 16.04
**Compiler name and version:** GCC 5.4.0
- The documentation for `channels/auspex` generically covers this scenario.

Add oper exemption to hidemode.

---

configure

Currently when you change the install paths interactively in ./configure, the example path remains set to the default. This results in the example files "hiding" in the wrong place. Since this option is more for system maintainers and scripted setups, I've just added a line to update the examples directory during the interactive path changes rather than give the option to define it there.
A quick test on Ubuntu 16.04 showed successful.
Reported by damian on IRC.

Update examples directory when paths are changed interactively.

---

src/modules/m_timedbans.cpp

Modify the messages sent for the setting and expiry of timed bans to be more informative and similar to each other. Some clients can be terrible with (channel) notices and/or users can choose to have all notices sent to a specific/active window. In these cases, a more informative message is very helpful.
```
Mode #chan +b a!*@c by @nick
[server.name] nick added a timed ban on a!*@c lasting for 15s.
[server.name] *** Timed ban on #chan expired.
Mode #chan -b a!*@c by server.name
```
```
Mode #chan +b a!*@c by @nick
[server.name] Timed ban a!*@c added by nick on #chan lasting for 15s.
[server.name] Timed ban a!*@c set by nick on #chan has expired.
Mode #chan -b a!*@c by server.name
```
Also cleaned up some formatting and comments.
Resolves #1639.  
Bring code and comment formatting up to …

m_timedbans: Minor improvements

---

src/modules/extra/m_ssl_gnutls.cpp
src/modules/extra/m_ssl_mbedtls.cpp
src/modules/extra/m_ssl_openssl.cpp

Send a server notice of a successful SSL module rehash.
SSL modules only rehash when specifically told to with `/rehash [-]ssl` or via signal using m_sslrehashsignal. Currently there is no confirmation of anything happening when called from IRC and only a notice of the rehash being called when done via signal. Confirmation of success (and just in general from IRC) has been requested a few times in #inspircd and is nice to have.
**Operating system name and version:** Ubuntu 16.04
**Compiler name and version:** GCC 5.4.0

SSL modules: send SNOTICE upon successful rehash.

---

src/configreader.cpp
src/modules/m_nationalchars.cpp

* Allow `options:casemapping` to remain defined and not cause rehash errors when another module is providing the current casemapping (i.e., m_nationalchars).
* m_nationalchars: Save the current CaseMapping value when loading and set it back when unloading, also rebuilding the ISupport numeric.
`options:casemapping` is defined in the example config and will cause a rehash to error out if m_nationalchars is loaded (CaseMapping is set different than the core expects). This is misleading and incorrect as the error implies you are trying to change the casemapping on rehash. The example config also claims it will be ignored if m_nationalchars is loaded, which is only half-true currently.
Setting the CaseMapping back when the module unloads is correct behavior and was just missed throughout …

Fix a couple of issues with m_nationalchars and casemapping.

---

src/modules/m_blockcolor.cpp
src/modules/m_noctcp.cpp
src/modules/m_nokicks.cpp
src/modules/m_nonicks.cpp
src/modules/m_nonotice.cpp

- Tell the user when they are extbanned rather than incorrectly say that the channel mode is set.
- Changed "Cannot" to "Can't" in m_nonicks to match the others.
- Refactored the logic in m_nonotice to match that of the others.
For the acting extbans that send a reply to the user, the implication that the channel mode is set can cause a lot of confusion. By switching up the message when they are extbanned (and the channel mode is **not** set), we can remedy the possible confusion.
**Operating system name and version:** Ubuntu 16.04
**Compiler name and version:** GCC 5.4.0

Acting extbans: Split the channel mode and extban replies.

---

src/modules/m_websocket.cpp

When checking the CIDR to see if IP is in proxy ranges, the call is done in wrong order. First item must be the user IP, then the range and finally the character map.
Also, the SetClientIP call is done if IP in proxy header is the same as proxy IP, and this should be the opposite.
To get the real user IP when websocket is behing a proxy.
I've setup a virtual machine with HAProxy:
```
global
log /dev/log  local0
log /dev/log  local1 notice
chroot /var/lib/haproxy
user haproxy
group haproxy
daemon
defaults
mode http
log global
option httplog
option  http-server-close
option  dontlognull
option  redispatch
option  contstats
retries 3
backlog 10000
timeout client          25s
timeout connect          5s
timeout server          25s
timeout tunnel        3600s
timeout http-keep-alive  1s …
```

Fixing MatchCIDR call when checking proxy range

---

docs/conf/modules.conf.example

Minor documentation clean-up.  The GUI doesn't show it but those are some kind of multi-byte spaces.

Clean special chars from module conf example

---

src/modules/extra/m_ldap.cpp
src/modules/m_ldapauth.cpp

Currently, it is difficult to diagnose LDAP authentication failures,
since the logs do not provide sufficient information about what is
actually being queried and what actually failed.
This increases logging details so that information about the LDAP query
is included, for example:
Fri Mar 06 2020 08:02:59 ANNOUNCEMENT: Error binding as manager to LDAP
server: Invalid credentials (bind dn=cn=adminz,dc=nodomain)
Rather than:
Fri Mar 06 2020 08:02:59 ANNOUNCEMENT: Error binding as manager to LDAP
server: Invalid credentials
Same with connection logging:
Fri Mar 06 2020 07:59:53 CONNECT: Forbidden connection from
jsing!jsing@192.168.200.1 (Invalid credentials (bind
dn=uid=jsing,dc=nodomain))
Fri Mar 06 2020 08:01:19 CONNECT: Successful connection from
jsing!jsing@192.168.200.1 …

Improve logging for the m_ldap and m_ldapauth modules

---

docs/conf/helpop.conf.example

Minor typo of a module name - `sslmode` -> `sslmodes`.
Typos are bad.
**Operating system name and version:** Ubuntu 18.04
**Compiler name and version:** GCC 7.5.0

Correct a module name typo.

---

include/convto.h

Fixes the incorrect conversion in the `ConvToNum` (un)signed char function overloads.
It should be matching - signed int with signed char and unsigned int with unsigned char.
**Operating system name and version:** Ubuntu 18.04
**Compiler name and version:** GCC 7.5.0
So far, the only place either of these overloads is used is in socket.cpp for the CIDR mask. I have tested this using `TLINE` and an IPv6 CIDR of /128. Before, it would match all IPv6 addresses as the conversion function return `0`. After, it matches correctly to just the /128 of the address. Along with testing other ranges (/0, /1, /64, etc) to verify they are still correct.
This **might** fix #1648 - at least the part where a /128 Z-line hits more then it should.

Fix the signed-ness within ConvToNum char overloads.

---

src/modules/m_dnsbl.cpp

Only send the DNSBL X-line addition SNOTICE locally.
`m_spanningtree` will send an SNOTICE to 'X' when adding a line. This results in two messages (albeit slightly different wording) for the same thing on remote servers (from where the DNSBL hit happened).
**Before:**
```
[ServerB] *** REMOTEXLINE: ServerA added timed Z-line for 173.244.44.78, expires in 1h (on Mon Mar 23 2020 04:16:10): Your host is listed in the DroneBL. For more information, please visit https://dronebl.org/lookup_branded?ip=173.244.44.78
[ServerB] *** REMOTEXLINE: From ServerA: Z-line added due to DNSBL match on 173.244.44.78 to expire in 1h (on Mon Mar 23 2020 04:16:10): Your host is listed in the DroneBL. For more information, please visit https://dronebl.org/lookup_branded?ip=173.244.44.78
```
**After:**
``` …
```

Only send a local X-line SNOTICE.

---

docs/conf/modules.conf.example
src/modules/m_timedbans.cpp

This allow to disable channel operator notices when a timed ban is set or unset.
In big channels with a lot of activity can be noisy, specially for clients that do not allow to ignore it.
1. Forked latest insp3 branch
2. Compiled with patch and launched with a simple config enabling m_timedbans.
3. Connected a user.
4. Executed TBAN. Channel operator notices are sent.
5. Updated modules config with:
`<timedbans send_notice="false">`
6. Executed TBAN again. Channel operator notices are not sent.
- By default, send_notice is enabled (current behaviour).
- Updated modules conf example to explain the new config tab to enable/disable notices.
**Operating system name and version:** Ubuntu Eoan
**Compiler name and version:** gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 …

Added option in timedbans conf to disable channel operator notices when ban is set/unset

---

docs/conf/helpop.conf.example
docs/conf/modules.conf.example
src/modules/m_cban.cpp

This PR updates m_cban to use InspIRCd::Match to enable glob matching.
The existing logic does not actually account for a globbed channel name.
Tested on the insp3 git as of commit d0c1741.
**Operating system name and version:** Linux 5.8.16
**Compiler name and version:** Clang 10.0.1

m_cban: Implement support for channel masks

---

src/modules/m_override.cpp

Improve  the wording of m_override's MODE handler 
The wording omits the channel and the wording may be misleading
None

m_override: Improve wording

---

docs/conf/inspircd.conf.example
docs/conf/modules.conf.example

- Document that exemptions configured in \<options:exemptchanops\> can be negated.
- Change the \<badnick\> example in inspircd.conf.example to another nick, since ChanServ is already covered by examples/services/generic.conf.example.
Because.
Not applicable.
**Operating system name and version:** Not applicable.
**Compiler name and version:** Not applicable.

Document that exemptions configured in <options:exemptchanops> can be negated, and change the <badnick> ChanServ example

---

src/modules/m_ldapoper.cpp

Currently m_ldapoper doesn't add the user's ident when checking whether user's IP is in the oper hosts. This pull request copies the wait that cmd_oper does:
https://github.com/inspircd/inspircd/blob/7a02052130721d83b43a349dc9b0650ad798fc08/src/coremods/core_oper/cmd_oper.cpp#L53
The ldapoper fails the matching host is the user's IP and not host.
**Operating system name and version:** Linux 5.4.0
**Compiler name and version:** GCC 9.3.0 with musl 1.1.24 (docker)
- [] I have documented any features added by this pull request.

Check the ident when checking against IP in ldapoper

---

src/modules/extra/m_argon2.cpp

It's `-largon2`, not `-llibargon2`. I've experienced build failures due to this.
Changes the default linker flags in libargon2 to `-libargon2` instead of `-llibargon2`
`-llibargon2` is not the proper default way to link to the library and breaks the build where `pkg-config`` isn't being used.
Multiple Linux systems, one running debian oldstable, one running Adelie Linux
* Debian oldstable GCC 6.3.0
* Adelie Linux GCC 8.3.0
- [N/A] If ABI changes have been made I have incremented MODULE_ABI in `moduledefs.h`.
- [N/A] I have documented any features added by this pull request.

Fix default linker flags in libargon2

---

include/modules.h
src/modules.cpp
src/modules/m_pbkdf2.cpp

* Make sure m_pbkdf2 knows about services already existing when it is loaded.
Get rid of bug #1818
Followed procedure outlined in #1818 before and after fix.
**Operating system name and version:** 
WSL 4.4.0-19041-Microsoft
**Compiler name and version:** 
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

 Fix issue where m_pbkdf2 was not aware of services loaded before it.

---

docs/conf/modules.conf.example
src/modules/m_repeat.cpp

Be able to setup a custom kick message.
It is useful to be able to customize the message with more descritive one and/or in another language for non-english networks.
Latest insp3 branch.
**Operating system name and version:** Debian 10.6
**Compiler name and version:** gcc 8.3.0

Implemented configurable kick message for module m_repeat

---

docs/conf/opers.conf.example
src/modules/m_sslinfo.cpp

This PR adds an `if-host-match` option to the (previously boolean) `autologin` functionality offered by the `sslinfo` module, for automatically logging opers in at connection time. If this option is set, then opers matching the given block will only be logged in if they have *both* a matching client certificate and a matching source host.
When logging into an oper block manually, the requesting client's source host is checked against the `host` setting in the oper block. However, automatic oper login provided by `sslinfo` does not otherwise check the source host, relying solely on the connecting client's certificate fingerprint. This PR adds the ability to also perform source host checking for automatic oper logins, both for consistency and as this might be a useful extra verification …

Add "if-host-match" option to sslinfo oper autologin

---

src/coremods/core_channel/cmd_names.cpp

Makes NAMES reply with RPL_ENDOFNAMES even for nonexisting channels
Instead of ERR_NOSUCHCHANNEL.
This is the behavior described by the RFCs and the Modern spec,
and is implemented by Hybrid/Chary/Solanum, Ergo, and Unreal.
**Operating system name and version:** Debian 10
**Compiler name and version:** GCC 8.3.0

Makes NAMES reply with RPL_ENDOFNAMES even for nonexisting channels

---

src/inspircd.cpp

It looks like ya_getopt increments `optind` between reading the argument and returning, so it needs to be decremented before accessing argv.
Before
```
$ ./build/GCC-8.3/bin/inspircd --foo bar
Error: unknown option 'bar'.
$ ./build/GCC-8.3/bin/inspircd --help
Error: unknown option '%
```
(`%` means there is no newline at the end)
After:
```
$ ./build/GCC-8.3/bin/inspircd --foo bar
Error: unknown option '--foo'.
Usage: ./build/GCC-8.3/bin/inspircd [--config <file>] [--debug] [--nofork] [--nolog]
[--nopid] [--runasroot] [--version]
$ ./build/GCC-8.3/bin/inspircd --help
Error: unknown option '--help'.
Usage: ./build/GCC-8.3/bin/inspircd [--config <file>] [--debug] [--nofork] [--nolog]
[--nopid] [--runasroot] [--version]
```
**Operating system name and …

Fix argv index error in 'unknown option' message.

---

docs/conf/modules.conf.example
docs/conf/opers.conf.example
src/modules/m_repeat.cpp

Allows network admins to make opers immune to repeat punishment (mode `+E`) via a config setting (`repeat/opersimmune`)
Resolves #1847
**Operating system name and version:** Debian 10
**Compiler name and version:** gcc version 8.3.0

m_repeat: allow opers to be immune to repeat punishment

---

src/coremods/core_mode.cpp

In InspIRCd 4.0.0a7, the `PREFIX` token in `RPL_ISUPPORT` was observed as `PREFIX=(Yqaohv)Yqaohv`. This commit fixes it so that this configuration would produce `PREFIX=(Yqaohv)!~&@%+`.
The existing behaviour is incorrect: the characters outside the brackets are supposed to be the prefix characters, not the mode letters. In particular, presenting letters as channel status prefixes could cause very messy behaviour in clients.
**Operating system name and version:** Ubuntu 20.04 under WSL 2
**Compiler name and version:** gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

Fix PREFIX in RPL_ISUPPORT

---

docs/conf/inspircd.conf.example
docs/conf/opers.conf.example
src/modules/m_delaymsg.cpp

This pull request tries to use HasPrivPermission and exemptchanops to be able to exclude operators or some channel ranks like op and voice from being affected by channel +d mode (delaymsg module).
- Condition that channel rank voice or upper is not affected is removed.
- Added condition to exempt operators with channels/ignore-delaymsg priv.
- Added condition to exempt users with CheckExemption::Call "delaymsg" so if you add delaymsg:v into exemptchanops all ranks equal or above voice (v) are not affected.
- Updated inspircd.conf.example to document new delaymsg option for exemptchanops.
- Updated opers.conf.example to document new operators privilege channels/ignore-delaymsg.
I have tested with latest insp3 branch.
**Operating system name and …

Insp3 fix delaymsg exemption

---

src/coremods/core_whowas.cpp

Reverse order of WHOWAS replies, so the most recent is first
To be consistent with other implementations + the RFCs:
* https://datatracker.ietf.org/doc/html/rfc1459#section-4.5.3
* https://datatracker.ietf.org/doc/html/rfc2812#section-3.6.3
**Operating system name and version:** Debian 11
**Compiler name and version:** GCC 10.2.1

Reverse order of WHOWAS replies

---

docs/conf/helpop.conf.example
src/coremods/core_whowas.cpp

Note: this PR includes the commit in #1967, because it touches the same line.
Add support for the <count> param of WHOWAS, which limits the number of returned replies
Not very useful IMO, but every server but InspIRCd seems to implement it, and it's part of the RFCs:
* https://datatracker.ietf.org/doc/html/rfc1459#section-4.5.3
* https://datatracker.ietf.org/doc/html/rfc2812#section-3.6.3
**Operating system name and version:** Debian 11
**Compiler name and version:** GCC 10.2.1

Add support for the <count> param of WHOWAS

---

make/template/logrotate

Previously-rotated logfiles would get rotated again, causing multiple
rehashes and very long file names.
```
ircd.log
ircd.log-20220522.gz
ircd.log-20220522.gz-20220605
ircd.log-20220522.gz-20220605-20220612
ircd.log-20220522.gz-20220605-20220612-20220619
ircd.log-20220522.gz-20220605-20220612-20220619-20220626
ircd.log-20220522.gz-20220605-20220612-20220619-20220626-20220703
ircd.log-20220529.gz
ircd.log-20220529.gz-20220612
ircd.log-20220529.gz-20220612-20220619
ircd.log-20220529.gz-20220612-20220619-20220626
ircd.log-20220529.gz-20220612-20220619-20220626-20220703
ircd.log-20220605.gz
ircd.log-20220605.gz-20220619
ircd.log-20220605.gz-20220619-20220626
ircd.log-20220605.gz-20220619-20220626-20220703
ircd.log-20220612.gz
ircd.log-20220612.gz-20220626 …
```

Fix logrotate conf bug

---

make/template/logrotate

Add OpenRC "support" to logrotate.
The current method doesn't work on Gentoo.  Gentoo installs files into `/lib/systemd` even though systemd might not be in use, causing the `systemctl` commands to be run (which fail).  Checking for OpenRC and running its specific rehash command before systemd fixes the issue.
**Operating system name and version:** Gentoo
**Compiler name and version:** GCC 11.3.0

Add OpenRC support to logrotate

---

src/modules/extra/m_ssl_openssl.cpp

Fixes issue where certificates which expire after 2049 might erroneously be marked as expired.
I generated certificates to last 'till 2120 in my test environment so I wouldn't have to deal with tests failing due to expiration.  The irony is rich.
Gentoo VM.
**Operating system name and version:** Gentoo!  `Linux test 5.15.88 #1 SMP Sun Feb 12 17:24:09 PST 2023 x86_64 QEMU Virtual CPU version 2.5+ GenuineIntel GNU/Linux`
**Compiler name and version:**  gcc (Gentoo Hardened 12.2.1_p20230428-r1 p2) 12.2.1 20230428

Fix cert expiration for dates after year 2049

---

docs/conf/help.conf.example

This PR solves issue 2034: missing documentation for /PROP in /help.
I went bug hunting and spotted this bug as something that I can quickly add.
This PR is against master, but also cleanly applies to insp3 if we want to backport.
This PR was tested with a minimal inspircd running stock inspircd.conf, including help.conf and modules.conf (help module only)
**Operating system name and version:** Not relevant, documentation change
**Compiler name and version:** Not relevant, documentation change

This commit adds documentation for /PROP

---

make/configure.pm

This is an attempt to fix issue 2070
clang++ does not have -v for --version, so call it by the long option
Interestingly the bug manifested very strangely on my machine - maybe user error too.
GOOD: CXX=clang++ ./configure
BAD: CXX=clang++ ./configure --disable-ownership
BAD: CXX=clang++ ./configure --disable-ownership | cat
BAD: CXX=clang++ ./configure | cat
People try to build inspircd using clang and this fails for example in https://bugs.gentoo.org/919508
**Operating system name and version:** 
**Compiler name and version:** 

Call $compiler with --version instead of -v

---

tools/convert-unreal-channel
tools/convert-unreal-tkl

This replaces string slicing with `io.Bytes`, which keeps the original string and moves a cursor.
Non-trivial string slicing on CPython makes a copy of the string, making the overall parsing run in quadratic time.
For example, assuming an average field size of 10 bytes, parsing a 1MB file on my computer would take 70s in slicing alone.
**Operating system name and version:** Debian 12.5
**Compiler name and version:** Python 3.11

tools/convert-unreal-*: Parse input in linear time

---

src/modules/extra/m_pgsql.cpp

The SQL row vector was not being cleared between iterations, causing values to accumulate and duplicate. This adds result.clear() before populating each row.
In order to be able to use the pgsql module effectively
**Operating system name and version:** Ubuntu22.04.1 (aarch64) / macOS Sequoia 15.1
**Compiler name and version:** GCC 11.4 / clang 16.0.0 (clang-1600.0.26.4)

fix: m_pgsql: Clear vector before adding new values to prevent duplicates

---

include/channels.h
src/coremods/core_who.cpp

On our server hosting 150K users was running hot and some perf captures turned up a few easy optimizations we thought we would share.
These two low-risk changes combined seem to have cut a few percent off of the CPU capture. 
These changes have been live in our production environment all day and there has been no problems.
Ubuntu 22.04.4 LTS
gcc version 11.4.0

Two simple performance optimizations for large servers

---

docs/conf/help.example.conf
docs/conf/inspircd.example.conf

Update example help configs with missing restriction exemptions, extbans and user and channel modes. Remove mentions of blockcaps as it doesn't exist anymore.
To keep the documentation updated.
Not applicable

Update example help configs with missing restriction exemptions, extbans and user and channel modes
