inspircd/inspircd

- configure
Another day; another misleading error message from configure.
> [2.0] Fix erroneous error messages in configure.

- extras/m_sqloper.mssql.sql
- extras/m_sqloper.mysql.sql
- extras/m_sqloper.postgresql.sql
- extras/m_sqloper.sqlite3.sql
- src/modules/m_sqloper.cpp
> m_sqloper: Add `active` column

- docs/conf/helpop-full.conf.example
- docs/conf/helpop.conf.example
- docs/conf/modules.conf.example
> Remove non-existant extban M: from docs

- configure
- include/modules/cap.h
- make/configure.pm
- make/console.pm
- tools/test-build
ec971cb72c3e9b1f1646a4c76ba1ddaf7c7221e5 will probably break Jenkins.
@tobgen can you change the Jenkinses to pass `--development` to configure?
> Various changes mainly relating to the build system.

- make/calcdep.pl
- make/unit-cc.pl
This problem was discovered by @Adam-.
> Fix modules with 2+ files not having their LinkerFlags parsed.

- src/modules/m_alias.cpp
> Add support for channel alias prefixes with multiple characters.

- docs/conf/helpop-full.conf.example
- docs/conf/helpop.conf.example
- docs/conf/modules.conf.example
- src/modules/m_repeat.cpp
Also update `docs/` accordingly.
> m_repeat: fix typo (similiar->similar)

- win/inspircd_win32wrapper.h
Microsoft are actually implementing standardised stuff now. Crikey.
> [2.0] Fix compilation with Microsoft Visual C++ 14.

- src/modules/m_hideoper.cpp
> [2.0] Fix hidden operators being shown in LUSERS.

- make/template/main.mk
This prevents problems caused by paths with spaces in them.
> [2.0] Quote paths in the makefile.

- src/modules/m_hideoper.cpp
> Fix a minor warning in m_hideoper on some systems.

- include/configreader.h
- src/channels.cpp
... and use it to fix topic setter truncation.
> Add a method which calculates the maximum mask length.

- make/template/main.mk
> Use the environment's CPPFLAGS as well as its CXXFLAGS.

- src/modules/m_lockserv.cpp
> Allow the reason for locking to be specified in m_lockserv.

- configure
- tools/genssl
- tools/test-build
This is the 3.0 equivalent of #1245.
> Update build system for the removal of . from @INC.

- .travis.yml
- make/calcdep.pl
- tools/travis-ci.sh
Also, fix pure static builds which were apparently broken on GCC but nobody noticed because nobody uses them (I still think we should remove support for them).
> [2.0] Backport the master Travis changes to insp20.

- configure
This is a lot more user friendly than expecting the user to set environment variables.
> Add interactive-mode support for setting the compiler binary.

- docs/conf/inspircd.conf.example
- include/logger.h
- src/inspircd.cpp
- src/logger.cpp
Also use the behaviour behind this to fix #1290.
> Allow <log> tags to specify how often logs should be flushed.

- docs/conf/services/atheme.conf.example
> Fix wrong service name for /infoserv in atheme.conf.example

- configure
- make/common.pm
- make/configure.pm
- make/console.pm
- modulemanager
This is the initial phase of the ModuleManager cleanup.  I've got a plan for getting rid of the terrible module list format but that will come in a future PR. I thought it would be good to get rid of a few of the low hanging fruit first.
> Initial ModuleManager cleanup.

- docs/conf/modules.conf.example
- Add an exception for IRC-Source.
- Remove an exception for SearchIRC.
- Remove an old exception for netsplit.
> [2.0] Update securelist exception list.

- docs/conf/modules.conf.example
Literally a few days after we released they decided to change their crawling domain. Argh.
https://twitter.com/theircsource/status/866890251423371267
> [2.0] Update the securelist exemption for IRC-Source's crawler.

- src/modules/m_md5.cpp
This is left over from the old hashing system that allowed you to customise these values.
> Remove some dead code from m_md5.

- docs/conf/modules.conf.example
- src/modules/m_permchannels.cpp
> Automatically apply +P to all permanent channels.

- .github/ISSUE_TEMPLATE.md
I think this would be helpful to improve bug reports and minimize support requests in the bugtracker.
Reference: https://github.com/blog/2111-issue-and-pull-request-templates
> Add issue template to avoid support requests in bugtracker

- tools/genssl
I have tested it locally on my machine and the output seems fine but it will require someone who knows more about CSRs (@Casey952 maybe?) to test further.
Fixes #1299
> Add support for generating a certificate signing request to genssl.

- include/inspircd.h
- include/modules/exemption.h
- src/coremods/core_channel/cmd_topic.cpp
- src/coremods/core_channel/core_channel.cpp
- src/coremods/core_channel/core_channel.h
- src/helperfuncs.cpp
- src/inspircd.cpp
- src/modules/m_auditorium.cpp
- src/modules/m_blockcaps.cpp
- src/modules/m_blockcolor.cpp
- src/modules/m_censor.cpp
- src/modules/m_chanfilter.cpp
- src/modules/m_exemptchanops.cpp
- src/modules/m_messageflood.cpp
- src/modules/m_nickflood.cpp
- src/modules/m_noctcp.cpp
- src/modules/m_nonicks.cpp
- src/modules/m_nonotice.cpp
- src/modules/m_repeat.cpp
- src/modules/m_services_account.cpp
- src/modules/m_stripcolor.cpp
~~This needs further testing to check it doesn't have any hidden bugs. If anyone is interested in helping test then poke me in \#inspircd.dev.~~
> Move the OnCheckExemption hook out of the core.

- docs/conf/modules.conf.example
- src/modules/m_cloaking.cpp
Basic modification to solve #1336 
Compiled but untested.
Maybe @bubthegreat  can test, as he requested this change.
> Make domainparts configureable

- docs/conf/helpop-full.conf.example
- docs/conf/helpop.conf.example
* Add character 'n' - connect class ban (m_classban) [a54497e]
* Move character 'U' from the Acting list to the Matching list as it matches and can be used with other acting bans. Also reword it to read "Matches" and have "module" at the end like the rest.
> Helpop Updates

- src/modules/m_cloaking.cpp
Servers will now correctly show whether a remote user has +x or not.
This fixes https://github.com/inspircd/inspircd/issues/1416.
> Fix m_cloaking umode desync

- src/modules/extra/m_ssl_openssl.cpp
The 'crlfile' argument can point to a file that contains valid CRLs.
The 'crlpath' argument can point to a directory which contains CRLs,
albeit in OpenSSL's special hashed/symlink format.  The 'crlmode' option
'chain' checks all certificates in the chain while the option 'leaf'
checks only the leaf certificate in a chain.
> Add OpenSSL CRLs.

- docs/conf/helpop-full.conf.example
- include/modules/shun.h
- src/modules/m_filter.cpp
- src/modules/m_shun.cpp
SHUN is now an available action in m_filter. This option will, of course, only work if m_shun is loaded.
This resolves #483.
> Add SHUN as a /filter action

- docs/conf/helpop-full.conf.example
- docs/conf/helpop.conf.example
Already fixed in master in 8587df2
> [2.0]: Helpop: Move extban 'U' from acting to matching

- src/modules/extra/m_ssl_openssl.cpp
Backported from 2afc1af4639ae2bbef397f4f6acc834950017d91.
> m_ssl_openssl: Remove deprecated API members.

- docs/conf/filter.conf.example
- docs/conf/helpop-full.conf.example
- src/modules/m_filter.cpp
m_filter: Add a warn action for notifying opers while still allowing the message through.
Thanks to @H7-25 (Simos) for the idea.
> m_filter: Add a warn action for notifying opers while still allowing the message through.

- docs/conf/filter.conf.example
- docs/conf/helpop-full.conf.example
- docs/conf/helpop.conf.example
- docs/conf/inspircd.conf.example
- docs/conf/modules.conf.example
- include/bancache.h
- include/configreader.h
- include/inspircd.h
- include/users.h
- include/xline.h
- src/coremods/core_xline/cmd_eline.cpp
- src/coremods/core_xline/cmd_gline.cpp
- src/coremods/core_xline/cmd_kline.cpp
- src/coremods/core_xline/cmd_qline.cpp
- src/coremods/core_xline/cmd_zline.cpp
- src/coremods/core_xline/core_xline.cpp
- src/coremods/core_xline/core_xline.h
- src/modules/m_cban.cpp
- src/modules/m_clearchan.cpp
- src/modules/m_connectban.cpp
- src/modules/m_dnsbl.cpp
- src/modules/m_filter.cpp
- src/modules/m_rline.cpp
- src/modules/m_shun.cpp
- src/modules/m_spanningtree/treesocket.h
- src/modules/m_svshold.cpp
- src/snomasks.cpp
- src/usermanager.cpp
- src/xline.cpp
This doesn't change any functionality, the only lines of changed code are changes to user-facing text. The rest are comment and/or documentation changes:
- Change any "-Line", ":Line", or "*line" to "-line" throughout the X-line code, comments, and documentation.
- Add periods to the end of some notices.
- Correct a typo in the Q-line code comments.
- Update the filter module documentation (shun addition).
Original idea/co-author: @Robby-
> Improve X-line text consistency and update docs.

- src/modules/m_spanningtree/away.cpp
Fix the away message empty check in m_spanningtree
> Fix away broadcast logic

- src/modules/m_httpd_stats.cpp
- Split each major section to its own function, which helps with general readability
- Added `/stats/general` and `/stats/users` subpages
- Added `<localusercount>` object to `<general>`
- Removed unneeded (and invalid) newlines in `<isupport>` list
> Refactor m_httpd_stats, add subpages

- src/modules/m_filter.cpp
* Deduplicate "FILTER" in some SNOTICES.
* Add the filter reason to removals to match with X-line removals now.
* Use the new DurationString() function for a standardized duration display when adding.
* Add X-line mask, duration, and expiry date to the action messages.
Request/idea credit to @Robby-.
> Improve the messages in m_filter.

- src/xline.cpp
> insp3: Fix BanCache entries existing after X-line expiry.

- include/modules/who.h
- src/coremods/core_who.cpp
- src/modules/m_hideoper.cpp
- src/modules/m_namesx.cpp
Replaces the dirty logic in m_hideoper and m_namesx
> Add Who::Request::GetFieldIndex to get field index

- make/template/inspircd.service
Add the User and Group options to the systemd service unit template file.
Resolves #1596.
> Add the User and Group options to the systemd service unit template file.

- docs/conf/helpop.conf.example
> Add umode O (override) to helpop.

- docs/conf/filter.conf.example
- docs/conf/helpop.conf.example
- src/modules/m_filter.cpp
Added flag_no_registered to m_filter module to exclude registered users from filters
> m_filter registered users flag exception for filters

- docs/conf/modules.conf.example
> fix example config for m_connflood

- src/modules/m_ircv3_ctctags.cpp
- src/modules/m_spanningtree/main.cpp
- src/modules/m_spanningtree/main.h
Also fixes accidentally copying incoming tags on TAGMSG when sending to
other users
> Fix msgid inconsistencies with TAGMSG

- include/modules.h
- src/modules.cpp
- src/usermanager.cpp
The purpose of this pull request is to allow modifying quit message like we can do with part message in OnUserPart event.
The change is just removing const from parameter to allow its modification in modules.
> Adding OnUserPreQuit event to allow quit message changes by modules.

- src/modules/m_deaf.cpp
- src/modules/m_filter.cpp
- src/modules/m_ircv3_echomessage.cpp
- src/modules/m_noctcp.cpp
- src/modules/m_services_account.cpp
- src/modules/m_silence.cpp
- src/modules/m_spanningtree/main.cpp
- src/modules/m_stripcolor.cpp
Switch-cases are a bit easier to read and can be optimized a bit nicer in most cases when doing `if (a.b == value) {} else if (a.b == value2)`.. etc
> Replace large if/else blocks for target.type with switches

- src/modules/m_denychans.cpp
Reported by @Cronus89 in #inspircd.dev.
> Fix whitelist check for a badchan redirect.

- src/modules/m_chanfilter.cpp
Partial implementation for #1674
> m_chanfilter: Apply filters to part messages

- docs/conf/modules.conf.example
- src/modules/m_alias.cpp
> m_alias: Add option to strip colors when matching

- .mailmap
Mapping my nickname (previous commits mostly) to my real name.
> Update the mailmap for myself.

- README.md
Fixes the repetition of 'on' in the README.
My first time looking at the inspircd repository, and I noticed the error.
N/A
> fix a repetition

- src/modules/m_sslinfo.cpp
Updated to match the recent docs update: https://github.com/inspircd/inspircd-docs/commit/59e27f2ce46a5186aa72cc6816c93ef14fb1f06a
> sslinfo: Improve the version reply.

- docs/conf/modules.conf.example
Fixes the example config for m_watch
The example config for m_watch uses the wrong config key
**Operating system name and version:** N/A 
**Compiler name and version:** N/A 
> Fix watch example config

- .github/workflows/ci-linux.yml
- .github/workflows/ci-macos.yml
- .gitignore
- configure
- docs/conf/modules.conf.example
- src/modules/extra/m_argon2.cpp
Resolves #1540
Adds a module for the Argon2 KDF.
**Operating system name and version:** 
WSL 4.4.0-19041-Microsoft
**Compiler name and version:** 
clang version 10.0.0-4ubuntu1
Target: x86_64-pc-linux-gnu
> Add m_argon2 to extra

- docs/conf/inspircd.conf.example
- docs/conf/links.conf.example
- docs/conf/modules.conf.example
This changes the remaining instances of "true", "on", "false" and "off" to "yes" and "no" in the example configs.
It had to be done.
Not applicable.
**Operating system name and version:** Not applicable.
**Compiler name and version:** Not applicable.
> Change the remaining instances of "true", "on", "false" and "off" to "yes" and "no" in the example configs.

- src/command_parse.cpp
- src/coremods/core_info/cmd_commands.cpp
- src/coremods/core_oper/cmd_oper.cpp
- src/coremods/core_serialize_rfc.cpp
- src/coremods/core_user/cmd_nick.cpp
- src/logger.cpp
- src/modules/m_check.cpp
- src/modules/m_cloaking.cpp
- src/modules/m_filter.cpp
- src/modules/m_httpd_stats.cpp
- src/modules/m_ircv3.cpp
- src/modules/m_nationalchars.cpp
- src/modules/m_override.cpp
- src/modules/m_permchannels.cpp
- src/modules/m_sasl.cpp
- src/modules/m_spanningtree/main.cpp
- src/modules/m_spanningtree/protocolinterface.cpp
- src/modules/m_svshold.cpp
- src/modules/m_xline_db.cpp
- src/users.cpp
- src/xline.cpp
- win/win32service.cpp
Signed-off-by: Herman Semenov <GermanAizek@yandex.ru>
Here are very simple edits that should not disrupt the structure and operability of the code, I accept your wishes for edits of my PR.
Linux 5.x
GCC 10.x.x
MSVC (Visual Studio 2019)
Win10
> Code refactor, fixed bugs and minor optimize

- src/coremods/core_oper/umode_s.cpp
- src/modules/m_namedmodes.cpp
- src/modules/m_nationalchars.cpp
- src/modules/m_sqloper.cpp
Signed-off-by: Herman Semenov <GermanAizek@yandex.ru>
> Used std::move where it is needed

- docs/conf/providers/irccloud.conf.example
See https://www.irccloud.com/networks
Replaces #1956
> Update IRCCloud IP ranges

- docs/conf/modules.example.conf
Fix strange characters in the example configuration.
The character was probably a typo.
Nope; I just used `git diff --cached`
**Operating system name and version:** 
**Compiler name and version:** 
> Remove weird char from sasl module comment

- docs/conf/inspircd.example.conf
This makes the configuration more consistent with the example files.
Changes the PID and log example files to use configuration variables.
This makes the example configuration more consistent.
I tested this as part of my custom configuration at https://github.com/clinew/inspircd/tree/cotss-v4.3.0
**Operating system name and version:** Gentoo Linux
**Compiler name and version:** gcc (Gentoo Hardened 13.3.1_p20240614 p17) 13.3.1 20240614
> Change PID example path from absolute to relative
